package com.quxueyuan.bean.domain.signup;

import java.io.Serializable;
import java.util.Date;

public class Classes implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.name
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.trainingcamp_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer trainingcampId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.curr_number
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private String currNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.max_number
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private String maxNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table classes
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.id
     *
     * @return the value of classes.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.id
     *
     * @param id the value for classes.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.name
     *
     * @return the value of classes.name
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.name
     *
     * @param name the value for classes.name
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.trainingcamp_id
     *
     * @return the value of classes.trainingcamp_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getTrainingcampId() {
        return trainingcampId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.trainingcamp_id
     *
     * @param trainingcampId the value for classes.trainingcamp_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setTrainingcampId(Integer trainingcampId) {
        this.trainingcampId = trainingcampId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.sku_id
     *
     * @return the value of classes.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.sku_id
     *
     * @param skuId the value for classes.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.teacher_id
     *
     * @return the value of classes.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.teacher_id
     *
     * @param teacherId the value for classes.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.curr_number
     *
     * @return the value of classes.curr_number
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public String getCurrNumber() {
        return currNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.curr_number
     *
     * @param currNumber the value for classes.curr_number
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setCurrNumber(String currNumber) {
        this.currNumber = currNumber == null ? null : currNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.max_number
     *
     * @return the value of classes.max_number
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public String getMaxNumber() {
        return maxNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.max_number
     *
     * @param maxNumber the value for classes.max_number
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setMaxNumber(String maxNumber) {
        this.maxNumber = maxNumber == null ? null : maxNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.status
     *
     * @return the value of classes.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.status
     *
     * @param status the value for classes.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.is_delete
     *
     * @return the value of classes.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.is_delete
     *
     * @param isDelete the value for classes.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.create_date
     *
     * @return the value of classes.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.create_date
     *
     * @param createDate the value for classes.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.update_date
     *
     * @return the value of classes.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.update_date
     *
     * @param updateDate the value for classes.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Classes other = (Classes) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getTrainingcampId() == null ? other.getTrainingcampId() == null : this.getTrainingcampId().equals(other.getTrainingcampId()))
            && (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId()))
            && (this.getTeacherId() == null ? other.getTeacherId() == null : this.getTeacherId().equals(other.getTeacherId()))
            && (this.getCurrNumber() == null ? other.getCurrNumber() == null : this.getCurrNumber().equals(other.getCurrNumber()))
            && (this.getMaxNumber() == null ? other.getMaxNumber() == null : this.getMaxNumber().equals(other.getMaxNumber()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTrainingcampId() == null) ? 0 : getTrainingcampId().hashCode());
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getTeacherId() == null) ? 0 : getTeacherId().hashCode());
        result = prime * result + ((getCurrNumber() == null) ? 0 : getCurrNumber().hashCode());
        result = prime * result + ((getMaxNumber() == null) ? 0 : getMaxNumber().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}