package com.quxueyuan.bean.domain.signup;

import java.io.Serializable;
import java.util.Date;

public class ClassActivate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.class_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.valid_term
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer validTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.valid_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.activate_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private String activateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_activate.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class_activate
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.id
     *
     * @return the value of class_activate.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.id
     *
     * @param id the value for class_activate.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.class_id
     *
     * @return the value of class_activate.class_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.class_id
     *
     * @param classId the value for class_activate.class_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.teacher_id
     *
     * @return the value of class_activate.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.teacher_id
     *
     * @param teacherId the value for class_activate.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.valid_term
     *
     * @return the value of class_activate.valid_term
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getValidTerm() {
        return validTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.valid_term
     *
     * @param validTerm the value for class_activate.valid_term
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setValidTerm(Integer validTerm) {
        this.validTerm = validTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.valid_date
     *
     * @return the value of class_activate.valid_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.valid_date
     *
     * @param validDate the value for class_activate.valid_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setValidDate(Date validDate) {
        this.validDate = validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.status
     *
     * @return the value of class_activate.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.status
     *
     * @param status the value for class_activate.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.activate_url
     *
     * @return the value of class_activate.activate_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public String getActivateUrl() {
        return activateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.activate_url
     *
     * @param activateUrl the value for class_activate.activate_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setActivateUrl(String activateUrl) {
        this.activateUrl = activateUrl == null ? null : activateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.is_delete
     *
     * @return the value of class_activate.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.is_delete
     *
     * @param isDelete the value for class_activate.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.create_date
     *
     * @return the value of class_activate.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.create_date
     *
     * @param createDate the value for class_activate.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_activate.update_date
     *
     * @return the value of class_activate.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_activate.update_date
     *
     * @param updateDate the value for class_activate.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_activate
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ClassActivate other = (ClassActivate) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getClassId() == null ? other.getClassId() == null : this.getClassId().equals(other.getClassId()))
            && (this.getTeacherId() == null ? other.getTeacherId() == null : this.getTeacherId().equals(other.getTeacherId()))
            && (this.getValidTerm() == null ? other.getValidTerm() == null : this.getValidTerm().equals(other.getValidTerm()))
            && (this.getValidDate() == null ? other.getValidDate() == null : this.getValidDate().equals(other.getValidDate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getActivateUrl() == null ? other.getActivateUrl() == null : this.getActivateUrl().equals(other.getActivateUrl()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_activate
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getClassId() == null) ? 0 : getClassId().hashCode());
        result = prime * result + ((getTeacherId() == null) ? 0 : getTeacherId().hashCode());
        result = prime * result + ((getValidTerm() == null) ? 0 : getValidTerm().hashCode());
        result = prime * result + ((getValidDate() == null) ? 0 : getValidDate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getActivateUrl() == null) ? 0 : getActivateUrl().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}