package com.quxueyuan.bean.domain.signup;

import java.io.Serializable;
import java.util.Date;

public class Operate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.trainingcamp_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer trainingcampId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.level_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.channel
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.poster_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private String posterUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.qr_code_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private String qrCodeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operate.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operate
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.id
     *
     * @return the value of operate.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.id
     *
     * @param id the value for operate.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.trainingcamp_id
     *
     * @return the value of operate.trainingcamp_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getTrainingcampId() {
        return trainingcampId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.trainingcamp_id
     *
     * @param trainingcampId the value for operate.trainingcamp_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setTrainingcampId(Integer trainingcampId) {
        this.trainingcampId = trainingcampId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.sku_id
     *
     * @return the value of operate.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.sku_id
     *
     * @param skuId the value for operate.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.level_id
     *
     * @return the value of operate.level_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.level_id
     *
     * @param levelId the value for operate.level_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.channel
     *
     * @return the value of operate.channel
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.channel
     *
     * @param channel the value for operate.channel
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.status
     *
     * @return the value of operate.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.status
     *
     * @param status the value for operate.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.poster_url
     *
     * @return the value of operate.poster_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public String getPosterUrl() {
        return posterUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.poster_url
     *
     * @param posterUrl the value for operate.poster_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setPosterUrl(String posterUrl) {
        this.posterUrl = posterUrl == null ? null : posterUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.qr_code_url
     *
     * @return the value of operate.qr_code_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public String getQrCodeUrl() {
        return qrCodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.qr_code_url
     *
     * @param qrCodeUrl the value for operate.qr_code_url
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setQrCodeUrl(String qrCodeUrl) {
        this.qrCodeUrl = qrCodeUrl == null ? null : qrCodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.is_delete
     *
     * @return the value of operate.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.is_delete
     *
     * @param isDelete the value for operate.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.create_date
     *
     * @return the value of operate.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.create_date
     *
     * @param createDate the value for operate.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operate.update_date
     *
     * @return the value of operate.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operate.update_date
     *
     * @param updateDate the value for operate.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Operate other = (Operate) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTrainingcampId() == null ? other.getTrainingcampId() == null : this.getTrainingcampId().equals(other.getTrainingcampId()))
            && (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId()))
            && (this.getLevelId() == null ? other.getLevelId() == null : this.getLevelId().equals(other.getLevelId()))
            && (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getPosterUrl() == null ? other.getPosterUrl() == null : this.getPosterUrl().equals(other.getPosterUrl()))
            && (this.getQrCodeUrl() == null ? other.getQrCodeUrl() == null : this.getQrCodeUrl().equals(other.getQrCodeUrl()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operate
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTrainingcampId() == null) ? 0 : getTrainingcampId().hashCode());
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getLevelId() == null) ? 0 : getLevelId().hashCode());
        result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getPosterUrl() == null) ? 0 : getPosterUrl().hashCode());
        result = prime * result + ((getQrCodeUrl() == null) ? 0 : getQrCodeUrl().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}