package com.quxueyuan.bean.domain.signup;

import java.io.Serializable;
import java.util.Date;

public class User2like implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.uid_from
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer uidFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.uid_to
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer uidTo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.course_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer skuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user2like.like_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date likeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user2like
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.id
     *
     * @return the value of user2like.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.id
     *
     * @param id the value for user2like.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.is_delete
     *
     * @return the value of user2like.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.is_delete
     *
     * @param isDelete the value for user2like.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.create_date
     *
     * @return the value of user2like.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.create_date
     *
     * @param createDate the value for user2like.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.update_date
     *
     * @return the value of user2like.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.update_date
     *
     * @param updateDate the value for user2like.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.status
     *
     * @return the value of user2like.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.status
     *
     * @param status the value for user2like.status
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.uid_from
     *
     * @return the value of user2like.uid_from
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getUidFrom() {
        return uidFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.uid_from
     *
     * @param uidFrom the value for user2like.uid_from
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUidFrom(Integer uidFrom) {
        this.uidFrom = uidFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.uid_to
     *
     * @return the value of user2like.uid_to
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getUidTo() {
        return uidTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.uid_to
     *
     * @param uidTo the value for user2like.uid_to
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUidTo(Integer uidTo) {
        this.uidTo = uidTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.course_id
     *
     * @return the value of user2like.course_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.course_id
     *
     * @param courseId the value for user2like.course_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.sku_id
     *
     * @return the value of user2like.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.sku_id
     *
     * @param skuId the value for user2like.sku_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user2like.like_date
     *
     * @return the value of user2like.like_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getLikeDate() {
        return likeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user2like.like_date
     *
     * @param likeDate the value for user2like.like_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setLikeDate(Date likeDate) {
        this.likeDate = likeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2like
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User2like other = (User2like) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUidFrom() == null ? other.getUidFrom() == null : this.getUidFrom().equals(other.getUidFrom()))
            && (this.getUidTo() == null ? other.getUidTo() == null : this.getUidTo().equals(other.getUidTo()))
            && (this.getCourseId() == null ? other.getCourseId() == null : this.getCourseId().equals(other.getCourseId()))
            && (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId()))
            && (this.getLikeDate() == null ? other.getLikeDate() == null : this.getLikeDate().equals(other.getLikeDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2like
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUidFrom() == null) ? 0 : getUidFrom().hashCode());
        result = prime * result + ((getUidTo() == null) ? 0 : getUidTo().hashCode());
        result = prime * result + ((getCourseId() == null) ? 0 : getCourseId().hashCode());
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getLikeDate() == null) ? 0 : getLikeDate().hashCode());
        return result;
    }
}