package com.quxueyuan.bean.domain.signup;

import java.io.Serializable;
import java.util.Date;

public class UserTeacher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher.user_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher.signup_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date signupDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher.signup_time
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date signupTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_teacher.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_teacher
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher.id
     *
     * @return the value of user_teacher.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher.id
     *
     * @param id the value for user_teacher.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher.user_id
     *
     * @return the value of user_teacher.user_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher.user_id
     *
     * @param userId the value for user_teacher.user_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher.teacher_id
     *
     * @return the value of user_teacher.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher.teacher_id
     *
     * @param teacherId the value for user_teacher.teacher_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher.signup_date
     *
     * @return the value of user_teacher.signup_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getSignupDate() {
        return signupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher.signup_date
     *
     * @param signupDate the value for user_teacher.signup_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setSignupDate(Date signupDate) {
        this.signupDate = signupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher.signup_time
     *
     * @return the value of user_teacher.signup_time
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getSignupTime() {
        return signupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher.signup_time
     *
     * @param signupTime the value for user_teacher.signup_time
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setSignupTime(Date signupTime) {
        this.signupTime = signupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher.is_delete
     *
     * @return the value of user_teacher.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher.is_delete
     *
     * @param isDelete the value for user_teacher.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher.create_date
     *
     * @return the value of user_teacher.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher.create_date
     *
     * @param createDate the value for user_teacher.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_teacher.update_date
     *
     * @return the value of user_teacher.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_teacher.update_date
     *
     * @param updateDate the value for user_teacher.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserTeacher other = (UserTeacher) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getTeacherId() == null ? other.getTeacherId() == null : this.getTeacherId().equals(other.getTeacherId()))
            && (this.getSignupDate() == null ? other.getSignupDate() == null : this.getSignupDate().equals(other.getSignupDate()))
            && (this.getSignupTime() == null ? other.getSignupTime() == null : this.getSignupTime().equals(other.getSignupTime()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_teacher
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTeacherId() == null) ? 0 : getTeacherId().hashCode());
        result = prime * result + ((getSignupDate() == null) ? 0 : getSignupDate().hashCode());
        result = prime * result + ((getSignupTime() == null) ? 0 : getSignupTime().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}