package com.quxueyuan.bean.domain.signup;

import java.io.Serializable;
import java.util.Date;

public class UserClass implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_class.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_class.class_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_class.user_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_class.join_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date joinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_class.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_class.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_class.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_class
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_class.id
     *
     * @return the value of user_class.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_class.id
     *
     * @param id the value for user_class.id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_class.class_id
     *
     * @return the value of user_class.class_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_class.class_id
     *
     * @param classId the value for user_class.class_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_class.user_id
     *
     * @return the value of user_class.user_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_class.user_id
     *
     * @param userId the value for user_class.user_id
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_class.join_date
     *
     * @return the value of user_class.join_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getJoinDate() {
        return joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_class.join_date
     *
     * @param joinDate the value for user_class.join_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_class.is_delete
     *
     * @return the value of user_class.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_class.is_delete
     *
     * @param isDelete the value for user_class.is_delete
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_class.create_date
     *
     * @return the value of user_class.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_class.create_date
     *
     * @param createDate the value for user_class.create_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_class.update_date
     *
     * @return the value of user_class.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_class.update_date
     *
     * @param updateDate the value for user_class.update_date
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_class
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserClass other = (UserClass) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getClassId() == null ? other.getClassId() == null : this.getClassId().equals(other.getClassId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getJoinDate() == null ? other.getJoinDate() == null : this.getJoinDate().equals(other.getJoinDate()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_class
     *
     * @mbggenerated Fri Nov 02 11:08:46 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getClassId() == null) ? 0 : getClassId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getJoinDate() == null) ? 0 : getJoinDate().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        return result;
    }
}